# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Time2Dev - Itinéraire d'un dev en dev!
email: alex@time2dev.fr
description: > # this means to ignore newlines until "baseurl:" 
  Ma vie, mon oeuvre, et beaucoup de choses à côté suivant l'inspiration. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.time2dev.fr" # the base hostname & protocol for your site
twitter_username: alex_fradet
github_username: Fradou

# Build settings
markdown: kramdown
